server:
  port: 8085
  servlet:
    context-path: /secure

spring:
  application:
    name: security-service
  datasource:
    username: root
    password: Think@123
    url: jdbc:mysql://localhost:3306/demo1
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: EMBEDDED
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION



